[package]
org = "healthcare_samples"
name = "carinbb_ballerina"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "healthcare_samples"
name = "carinbb_package"
version = "0.0.1"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "healthcare.fhir.r4"
version = "4.0.0"
